name: Docker image build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: >-
        docker build . \
          --build-arg=BUILD_SERIES=dev \
          --build-arg=BUILD_ID="$(echo "$GITHUB_SHA" | head -c 12)" \
          --tag snikket/snikket-web-portal:dev
    - name: Log into registry
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u snikket --password-stdin
    - name: Push the Docker image
      run: docker push snikket/snikket-web-portal:dev
